name: Autocommit 5 Times a Day

on:
  schedule:
    # Menjadwalkan agar job ini berjalan 5 kali sehari (setiap 4 jam)
    - cron: "0 0,4,8,12,16 * * *"
  workflow_dispatch:

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "NCholisM"
          git config --global user.email "cholis789rt@gmail.com"

      - name: Create commit
        run: |
          # Membuat perubahan di file yang ingin di-commit
          echo "Autocommit at $(date)" >> autocommit.txt
          git add autocommit.txt
          git commit -m "Autocommit at $(date)"
          git push https://github.com/${{ github.repository }} HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
