name: Autocommit Custom Schedule

on:
  schedule:
    - cron: "0 0 * * *" # Menjalankan setiap hari pada pukul 07:00 WIB
  workflow_dispatch: # Bisa dijalankan manual juga

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Menghindari error merge

      - name: Set up Git
        run: |
          git config --global user.name "NCholisM"
          git config --global user.email "cholis789rt@gmail.com"

      - name: Pull latest changes
        run: |
          git pull --rebase origin main # Menarik perubahan terbaru

      - name: Determine commit count
        run: |
          DAY_OF_WEEK=$(date +"%A") # Ambil nama hari (Senin, Selasa, dll.)
          case $DAY_OF_WEEK in
            Monday) COMMIT_COUNT=10 ;;
            Tuesday) COMMIT_COUNT=20 ;;
            Wednesday) COMMIT_COUNT=30 ;;
            Thursday) COMMIT_COUNT=40 ;;
            Friday) COMMIT_COUNT=50 ;;
            Saturday) COMMIT_COUNT=60 ;;
            Sunday) COMMIT_COUNT=70 ;;
          esac

          echo "Commit Count: $COMMIT_COUNT" # Cek berapa commit yang dibuat hari ini

          for i in $(seq 1 $COMMIT_COUNT); do
            echo "Autocommit #$i at $(date)" >> autocommit.txt
            git add autocommit.txt
            git commit --author="NCholisM <cholis789rt@gmail.com>" -m "Autocommit #$i at $(date)"
          done

      - name: Push changes
        run: |
          git push https://oauth2:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
