name: Update Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Menjalankan setiap hari pada tengah malam UTC
  workflow_dispatch: # Menambahkan opsi untuk menjalankan workflow secara manual

jobs:
  update-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Auto-commit
        run: |
          echo "Auto update on $(date)" >> README.md
          git config user.name "NCholisM"
          git config user.email "cholis789rt@gmail.com"
          git add .
          git commit -m "Auto commit on $(date)" || echo "No changes to commit"
          git push
