name: Autocommit 5 Times a Day

on:
  schedule:
    - cron: "0 0,4,8,12,16 * * *"
  workflow_dispatch:

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Mengambil seluruh riwayat git untuk menghindari error merge

      - name: Set up Git
        run: |
          git config --global user.name "NCholisM"
          git config --global user.email "cholis789rt@gmail.com"

      - name: Pull latest changes
        run: |
          git pull --rebase origin main  # Menarik perubahan terbaru

      - name: Create commit
        run: |
          echo "Autocommit at $(date)" >> autocommit.txt
          git add autocommit.txt
          git commit -m "Autocommit at $(date)" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push https://oauth2:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
